---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 130.193.40.223
    jenkins-agent-01:
      ansible_host: 130.193.40.65
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: masterci